server:
  port: 3000
  servlet:
    context-path: "/api"
spring:
  jpa:
    hibernate.ddl-auto: update
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate.check_nullability: true
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
  security:
    user:
      name: user
      password: user 